-- MySQL Script generated by MySQL Workbench
-- Fri Apr  5 16:02:26 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `albumes` DEFAULT CHARACTER SET utf8 ;
USE `albumes` ;

-- -----------------------------------------------------
-- Table `mydb`.`GENRE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `albumes`.`GENRE` (
  `idGenre` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `Genre` VARCHAR(255) NULL,
  PRIMARY KEY (`idGenre`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ARTIST`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `albumes`.`ARTIST` (
  `idArtist` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `artistName` VARCHAR(255) NULL,
  PRIMARY KEY (`idArtist`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ALBUM`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `albumes`.`ALBUM` (
  `idAlbum` INT NOT NULL AUTO_INCREMENT,
  `albumName` VARCHAR(255) NULL,
  `dateReleased` DATETIME NULL,
  `GENRE_idGenre` INT UNSIGNED NOT NULL,
  `ARTIST_idArtist` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idAlbum`, `GENRE_idGenre`),
  INDEX `fk_ALBUM_GENRE_idx` (`GENRE_idGenre` ASC) VISIBLE,
  INDEX `fk_ALBUM_ARTIST1_idx` (`ARTIST_idArtist` ASC) VISIBLE,
  CONSTRAINT `fk_ALBUM_GENRE`
    FOREIGN KEY (`GENRE_idGenre`)
    REFERENCES `albumes`.`GENRE` (`idGenre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ALBUM_ARTIST1`
    FOREIGN KEY (`ARTIST_idArtist`)
    REFERENCES `albumes`.`ARTIST` (`idArtist`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
