-- MySQL Script generated by MySQL Workbench
-- Fri Apr  5 16:26:23 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ciclo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ciclo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ciclo` DEFAULT CHARACTER SET utf8 ;
USE `ciclo` ;

-- -----------------------------------------------------
-- Table `ciclo`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclo`.`alumnos` (
  `id_alumnos` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(55) NOT NULL,
  `años` INT NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `nota_media` DECIMAL NOT NULL,
  PRIMARY KEY (`id_alumnos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclo`.`MODULOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclo`.`MODULOS` (
  `id_modulo` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ufs` INT NOT NULL,
  `descripcion_modulo` VARCHAR(55) NOT NULL,
  `horas` INT NOT NULL,
  `aulas` INT NOT NULL,
  PRIMARY KEY (`id_modulo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ciclo`.`alumnos_has_MODULOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ciclo`.`alumnos_has_MODULOS` (
  `alumnos_id_alumnos` INT UNSIGNED NOT NULL,
  `MODULOS_id_modulo` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`alumnos_id_alumnos`, `MODULOS_id_modulo`),
  INDEX `fk_alumnos_has_MODULOS_MODULOS1_idx` (`MODULOS_id_modulo` ASC) VISIBLE,
  INDEX `fk_alumnos_has_MODULOS_alumnos_idx` (`alumnos_id_alumnos` ASC) VISIBLE,
  CONSTRAINT `fk_alumnos_has_MODULOS_alumnos`
    FOREIGN KEY (`alumnos_id_alumnos`)
    REFERENCES `ciclo`.`alumnos` (`id_alumnos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumnos_has_MODULOS_MODULOS1`
    FOREIGN KEY (`MODULOS_id_modulo`)
    REFERENCES `ciclo`.`MODULOS` (`id_modulo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
